### PR TITLE
0.4.0 release version bump

### PR DESCRIPTION
**Pull request by BSchilperoort**

### CODE REVIEW

**Comment by BSchilperoort** [comment]
Hm. git workflows seem broken

**Comment by BSchilperoort** [comment]
Seems like some github issue. Things are green now.

**Review by slevang — APPROVED** [review]
I reran and they worked, no idea why :shrug: . I don't have permissions on RTD but looks like you got that one through.

**Comment by BSchilperoort** [comment]
>  I don't have permissions on RTD but looks like you got that one through.

Sent you an invite

**Comment by slevang** [comment]
Had a bit of a revelation with #51, let's get that in before release :smile:

**Comment by BSchilperoort** [comment]
> Had a bit of a revelation with #51, let's get that in before release 😄

OK!

**Pull request merged**
